const STATE={data:null,current:'all'};
const CATEGORY_ORDER=['all','daily_special','jeffrey_today','weather','busy_office','fitness_lifestyle','healthy_lifestyle','recovery','senior_safe','long_time_no_see','favourite','archive'];
const CATEGORY_LABELS={all:'全部',daily_special:'⭐ 今日精選',jeffrey_today:'☕ Jeffrey Today',weather:'🌦 天氣背景',busy_office:'💼 上班族',fitness_lifestyle:'🔥 Keep Fit',healthy_lifestyle:'🥗 健康生活',recovery:'🧘 Recovery',senior_safe:'👴 銀髮安全',long_time_no_see:'🫶 久未聯絡',favourite:'❤️ Favourite',archive:'📚 Archive'};
const $=id=>document.getElementById(id);
function getStore(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch(e){return fallback}}
function setStore(key,val){localStorage.setItem(key,JSON.stringify(val))}
function flattenMessages(data){const list=[];(data.dailySpecial||[]).forEach(m=>list.push({...m,category:'daily_special',daily:true}));(data.jeffreyToday||[]).forEach(m=>list.push({...m,category:'jeffrey_today',daily:true}));Object.entries(data.groups||{}).forEach(([category,items])=>items.forEach(m=>list.push({...m,category,daily:true})));(data.weatherMessages||[]).forEach(m=>list.push({...m,category:'weather',daily:true}));(data.archive||[]).forEach(m=>list.push({...m,category:'archive'}));return list}
function getFavouriteMessages(){const fav=getStore('jeffreyFavourites',{});return Object.values(fav)}
function renderBrief(){const d=STATE.data; $('dailyBrief').innerHTML=`<div class="brief-grid"><div class="brief-card"><h3>今日主題</h3><p>${d.theme||''}</p></div><div class="brief-card"><h3>香港生活脈搏</h3><p>${d.lifePulse||''}</p></div><div class="brief-card"><h3>天氣角色</h3><p>${d.weatherContext?.summary||''}<br>${d.weatherContext?.role==='background_only'?'天氣只做背景，不做主題。':''}</p></div></div>`}
function renderTabs(){const tabs=$('tabs');tabs.innerHTML='';CATEGORY_ORDER.forEach(cat=>{const b=document.createElement('button');b.className='tab'+(STATE.current===cat?' active':'');b.textContent=CATEGORY_LABELS[cat]||cat;b.onclick=()=>{STATE.current=cat;renderTabs();renderMessages()};tabs.appendChild(b)})}
function selectedMessages(){if(!STATE.data)return[];if(STATE.current==='favourite')return getFavouriteMessages().map(m=>({...m,category:'favourite',fav:true}));const all=flattenMessages(STATE.data);if(STATE.current==='all')return all.filter(m=>m.category!=='archive').slice(0,60);return all.filter(m=>m.category===STATE.current)}
function messageKey(m){return m.id||`${m.category}|${m.topic}|${m.content}`}
function renderMessages(){const grid=$('messageGrid');const used=getStore('jeffreyUsage',{});const fav=getStore('jeffreyFavourites',{});const items=selectedMessages();grid.innerHTML='';if(!items.length){grid.innerHTML='<div class="loading">暫時未有內容。</div>';return}items.forEach(m=>{const key=messageKey(m);const isFav=!!fav[key]||m.fav;const isUsed=!!used[key];const card=document.createElement('article');card.className='card'+(m.daily?' daily':'')+(isFav?' fav':'');card.innerHTML=`<div><div class="meta"><span class="pill">${CATEGORY_LABELS[m.category]||m.category}</span>${m.daily?'<span class="pill today">今日新增</span>':''}${m.humanScore?`<span class="pill score">Human ${m.humanScore}</span>`:''}</div><div class="topic">${m.topic||''}</div><div class="content">${m.content||''}</div>${isUsed?'<div class="usage">已 Copy 過，可避免重複發送</div>':''}</div><div class="card-actions"><button class="btn" data-copy="${key}">📋 Copy</button><button class="btn secondary" data-fav="${key}">${isFav?'❤️ 已收藏':'♡ Favourite'}</button></div>`;grid.appendChild(card);card.querySelector('[data-copy]').onclick=()=>copyMessage(m,key,card.querySelector('[data-copy]'));card.querySelector('[data-fav]').onclick=()=>toggleFav(m,key)})}
function copyMessage(m,key,btn){navigator.clipboard.writeText(m.content||'').then(()=>{const used=getStore('jeffreyUsage',{});used[key]={...m,lastCopied:new Date().toISOString(),count:(used[key]?.count||0)+1};setStore('jeffreyUsage',used);btn.textContent='✅ 已 Copy';btn.classList.add('copied');setTimeout(renderMessages,700)}).catch(()=>{alert('未能使用 Clipboard，請手動複製。')})}
function toggleFav(m,key){const fav=getStore('jeffreyFavourites',{});if(fav[key])delete fav[key];else fav[key]={...m,savedAt:new Date().toISOString()};setStore('jeffreyFavourites',fav);renderMessages()}
async function boot(){try{const r=await fetch('data/today.json?ts='+Date.now());if(!r.ok)throw new Error('today.json not found');STATE.data=await r.json();renderBrief();renderTabs();renderMessages()}catch(e){$('dailyBrief').innerHTML='<div class="loading">載入失敗：請檢查 data/today.json。</div>';console.error(e)}}
$('resetFilter').onclick=()=>{STATE.current='all';renderTabs();renderMessages()};
boot();
